version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - PROXY_DOMAIN=https://s3-ap-northeast-1.amazonaws.com
